lang: ruby

rvm:
  - 2.4.0

before_install:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-feed
  - gem install jekyll-archives
  
script:
  - jekyll build -d buildilo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: buildilo
  target_branch: master
  fqdn: pullrequest.ir
  repo: pr-techblog/pr-techblog.github.io
  on:
    branch: master
